version: '3.8'

services:
  
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./images:/usr/share/nginx/images:ro

  nginx_proxy:
    image: nginx
    ports:
      - 5080:80
    volumes:
      - ./nginx_proxy.conf:/etc/nginx/conf.d/default.conf
